travel_planner/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.db import router
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from travel_group import views

from accommodations.views import AccommodationListView, AccommodationDetailView, AccommodationCreateView, \
    AccommodationEditView, AccommodationDeleteView, AccommodationListTravelGroupView
from travel_users.views import UserLoginView, ProfileView, ProfileEditView, UserSignupView, UserSignupSuccessView, \
    UserLogoutView, ChecklistAllView
from travel_group.views import TravelGroupListView, TravelGroupSingleView, TravelGroupCreateView, SightseeingEditView, \
    RestaurantEditView, MessageEditView, SightseeingAddView, SightseeingDeleteView, RestaurantDeleteView, \
    RestaurantAddView, TravelerAccommodationListView, MessageAddView, TravelGroupChecklistView, \
    TravelGroupChecklistEditView, TravelGroupChecklistList, TravelGroupChecklistDelete, ChecklistViewSet, \
    MessageDeleteView, TravelGroupEditView, TravelGroupImage, InviteFormView, TravelGroupAddTraveler, \
    TravelGroupRemoveUserView, TravelGroupInvitePendingView, TravelGroupInviteSentView
from travel_transportation.views import TransportationEditView, TransportationCreateView, TransportationListView, \
    TransportationDetailView, TransportationDeleteView

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'checklist', ChecklistViewSet)


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('accommodation-list/<username>', AccommodationListView.as_view(), name="accommodation_list"),
    path('accommodation-list/for/<username>/<int:pk>', AccommodationListTravelGroupView.as_view(),
         name="accommodation_list_travelgroup"),
    path('accommodation-detail/<slug:username>/<pk>', AccommodationDetailView.as_view(), name="accommodation_detail"),
    path('accommodation-create', AccommodationCreateView.as_view(), name="accommodation_create"),
    path('accommodation-edit/<pk>', AccommodationEditView.as_view(), name="accommodation_edit"),
    path('accommodation-delete/<pk>', AccommodationDeleteView.as_view(), name="accommodation_delete"),
    path('admin/', admin.site.urls),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<slug:username>/', ProfileView.as_view(), name="profile"),
    path('edit/<slug:username>/', ProfileEditView.as_view(), name='edit'),
    path('checklists/for/<slug:username>/', ChecklistAllView.as_view(), name="checklists"),
    path('signup/<int:travel_group_id>/', UserSignupView.as_view(), name="signup"),
    path('signup/', UserSignupView.as_view(), name="signup"),
    path('signup/success/', UserSignupSuccessView.as_view(), name="signup_success"),
    path('travel-group/create/', TravelGroupCreateView.as_view(), name="travel_group_create"),
    path('travel-group/invite-sent/<int:pk>/', TravelGroupInviteSentView.as_view(), kwargs={'recipient': ''},
         name="travel_group_invite_sent"),
    path('travel-group/invite-pending/<int:pk>/<slug:username>', TravelGroupInvitePendingView.as_view(),
         name="travel_group_invite_pending"),
    path('travel-group/remove-user/<int:pk>/<slug:username>', TravelGroupRemoveUserView.as_view(),
         name="travel_group_remove_user"),
    path('travel-group-invite-form/<int:pk>/<slug:username>', InviteFormView.as_view(), name="invite-form"),
    path('travel-group/edit/<int:pk>', TravelGroupEditView.as_view(), name="travel_group_edit"),
    path('travel-group/sightseeing-edit/<int:pk>/', SightseeingEditView.as_view(), name="sightseeing_edit"),
    path('travel-group/sightseeing-add/<int:pk>', SightseeingAddView.as_view(), name="sightseeing_add"),
    path('travel-group/sightseeing-delete/<int:pk>', SightseeingDeleteView.as_view(), name="sightseeing_delete"),
    path('travel-group/restaurant-edit/<int:id>', RestaurantEditView.as_view(), name="restaurant_edit"),
    path('travel-group/restaurant-delete/<int:id>', RestaurantDeleteView.as_view(), name="restaurant_delete"),
    path('travel-group/restaurant-add/<int:id>', RestaurantAddView.as_view(), name="restaurant_add"),
    path('travel-group/<int:id>/message-edit/', MessageEditView.as_view(), name="message_edit"),
    path('travel-group/message-add/<int:id>', MessageAddView.as_view(), name="message_add"),
    path('travel-group/message-delete/<int:pk>', MessageDeleteView.as_view(), name="message_delete"),
    path('travel-group/checklist-add/<int:id>/<slug:username>', TravelGroupChecklistView.as_view(), name="travel_checklist_create"),
    path('travel-group/checklist-edit/<int:pk>/<slug:username>', TravelGroupChecklistEditView.as_view(), name="travel_checklist_edit"),
    path('travel-group/checklist-update', TravelGroupChecklistEditView.as_view(), name="travel_checklist_update"),
    path('travel-group/checklist-delete/<int:pk>/<slug:username>', TravelGroupChecklistDelete.as_view(), name="travel_checklist_delete"),
    path('travel-group/checklist-list/<int:id>/<slug:username>', TravelGroupChecklistList.as_view(), name="travel_checklist_list"),
    path('travel-group/for/<slug:username>/', TravelGroupListView.as_view(), name="travel_group_index"),
    path('travel-group/accommodations/<int:pk>/<slug:username>', TravelerAccommodationListView.as_view(), name="traveler_accommodation"),
    path('travel-group/<int:pk>/', TravelGroupSingleView.as_view(), name="travel_group_single"),
    path('travel-group/<int:pk>/add-traveler', TravelGroupAddTraveler.as_view(), name="add_traveler"),
    path('transportation-list/<slug:username>', TransportationListView.as_view(), name="transportation_list"),
    path('transportation-detail/<slug:username>/<int:pk>', TransportationDetailView.as_view(), name="transportation_detail"),
    path('transportation-create/<int:pk>', TransportationCreateView.as_view(), name="transportation_create"),
    path('transportation-edit/<int:pk>', TransportationEditView.as_view(), name="transportation_edit"),
    path('transportation-delete/<int:pk>', TransportationDeleteView.as_view(), name="transportation_delete"),
    url(r"^invitations/", include("pinax.invitations.urls", namespace="pinax_invitations")),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('api-unsplash/', TravelGroupImage.as_view(), name="unsplash"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

travel_group/models.py
from datetime import datetime

from django.db import models
# from travel_users.models import CustomUser
from djrichtextfield.models import RichTextField

from accommodations.models import Accommodations
from travel_transportation.models import Transportation


class UnsplashPhotos(models.Model):
    photo = models.CharField(max_length=400, blank=True)
    photo_attribution = models.CharField(max_length=600, blank=True)
    travel_group = models.ForeignKey('TravelGroup', related_name='unsplash_photo', on_delete=models.CASCADE)

    def __str__(self):
        return self.photo


class TravelGroup(models.Model):
    accommodations = models.ForeignKey(Accommodations, related_name='accommodation', on_delete=models.SET_NULL, null=True, blank=True)
    # photo = models.ForeignKey(UnsplashPhotos, related_name='display_photo', on_delete=models.SET_NULL, null=True,
    #                           blank=True)
    primary_destination = models.CharField(max_length=200, null=False, blank=False, default='')
    transportation = models.ForeignKey(Transportation, related_name='transportation', on_delete=models.SET_NULL,
                                       null=True, blank=True)
    travelers = models.ManyToManyField('travel_users.CustomUser', related_name='trav_groups', null=True, blank=True)
    group_owner = models.ForeignKey('travel_users.CustomUser', related_name='travel_group_owner', default=1,
                                    null=True, blank=False, on_delete=models.SET_NULL)
    trip_name = models.CharField(max_length=200, blank=False)

    def travel_group(self):
        group = self.objects.all()
        return group

    def get_context_data(self, **kwargs):
        context = super.get_context_data(**kwargs)

    def __str__(self):
        return self.trip_name


class ChecklistItems(models.Model):
    checklist_item = RichTextField(blank=True)
    checklist_creator = models.ForeignKey('travel_users.CustomUser', related_name='checklist_creator', on_delete=models.CASCADE)
    item_status = models.BooleanField(default=False)
    travel_group = models.ForeignKey('TravelGroup', related_name='checklist_items', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Checklist Items'

    def __str__(self):
        return self.checklist_item


class SightseeingIdeas(models.Model):
    sightseeing_idea = RichTextField(blank=True)
    sightseeing_creator = models.ForeignKey('travel_users.CustomUser', related_name='sightseeing_creator',
                                            on_delete=models.CASCADE, default=1)
    travel_group = models.ForeignKey('TravelGroup', related_name='sightseeing_ideas', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Sightseeing Idea'

    def __str__(self):
        return self.sightseeing_idea


class RestaurantIdeas(models.Model):
    restaurant_idea = RichTextField(blank=True)
    restaurant_creator = models.ForeignKey('travel_users.CustomUser', related_name='restaurant_creator',
                                            on_delete=models.CASCADE, default=1)
    travel_group = models.ForeignKey('TravelGroup', related_name='restaurant_ideas', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Restaurant Idea'

    def __str__(self):
        return self.restaurant_idea


class TravelMessages(models.Model):
    date_created_at = models.DateTimeField(default=datetime.now)
    date_updated_at = models.DateTimeField(default=datetime.now)
    message = RichTextField(blank=True)
    travel_group = models.ForeignKey('TravelGroup', related_name='messages', on_delete=models.CASCADE)
    message_creator = models.ForeignKey('travel_users.CustomUser', related_name='message_creator', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Travel Message'

    def __str__(self):
        return self.message


# class TravelGroupInvite(models.Model):
#     invitation = get_invitation_model()
#     recipient_email = models.EmailField(null=False, blank=False)
#     subject_line = models.CharField(max_length=300, blank=True, default="Join my travel group on Travel Planner")
#     travel_group = models.ForeignKey('TravelGroup', related_name='travel_group_invite', on_delete=models.CASCADE)
#
#     class Meta:
#         verbose_name = 'Travel Group Invite'
#
#     def __str__(self):
#         return self.travel_group

travel_group/forms.py
from typing import Type, Optional, Any, Callable, Iterable

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.forms import ModelForm, BaseModelFormSet, BaseModelForm, HiddenInput, TextInput, EmailInput
from django import forms
from django.forms.utils import ErrorList
from django.shortcuts import get_object_or_404

from travel_group.models import TravelGroup, SightseeingIdeas, RestaurantIdeas, TravelMessages, ChecklistItems, \
    UnsplashPhotos
from django.forms.models import inlineformset_factory

from travel_users.models import CustomUser


class GroupCreateForm(ModelForm):

    class Meta:
        model = TravelGroup
        fields = ['travelers', 'trip_name', 'primary_destination']
        widgets = {
            'travelers': TextInput(attrs={'size': '40', 'title': 'Type first and last name of traveler'}),
        }


class AddUserForm(forms.Form):
    traveler = forms.EmailField(required=True)
    template_name = 'travel_group/update-travelers.html'


class RemoveUserForm(forms.Form):
    traveler = forms.BooleanField(initial=True)
    template_name = 'travel_group/remove-travelers.html'


# class AddUserForm(ModelForm):
#
#     def __init__(self, *args, **kwargs):
#         super(AddUserForm, self).__init__(*args, **kwargs)
#         # Set the initial value to a blank string
#         self.initial['travelers'] = ''
#
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         # if User.objects.filter(email=email).exists():
#         #     raise ValidationError("Email already exists")
#         # return email
#
#     class Meta:
#         model = TravelGroup
#         fields = ['travelers', 'trip_name', 'primary_destination']
#         widgets = {
#             'travelers': EmailInput(attrs={'title': "Enter the email of the traveler you'd like to add",
#                                            'placeholder': "traveler@gmail.com"}),
#             'trip_name': HiddenInput(),
#             'primary_destination': HiddenInput(),
#         }
        # error_messages = {
        #     'travelers': {
        #         'invalid': "This email doesn't correspond to an existing user",
        #     }
        # }



class SightseeingCreateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        travel_group = get_object_or_404(TravelGroup, id=kwargs.pop('travel_group'))
        super().__init__(*args, **kwargs)
        self.fields['travel_group'].initial = travel_group

    class Meta:
        model = SightseeingIdeas
        fields = ['sightseeing_idea', 'travel_group']
        widgets = {
            'travel_group': HiddenInput()
        }


class SightseeingEditForm(ModelForm):

    class Meta:
        model = SightseeingIdeas
        fields = ['sightseeing_idea']


class RestaurantCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        travel_group = get_object_or_404(TravelGroup, id=kwargs.pop('travel_group'))
        super().__init__(*args, **kwargs)
        self.fields['travel_group'].initial = travel_group
        self.fields['travel_group'].widget = forms.HiddenInput()

    class Meta:
        model = RestaurantIdeas
        fields = ['restaurant_idea', 'travel_group']


class RestaurantEditForm(ModelForm):
    class Meta:
        model = RestaurantIdeas
        fields = ['restaurant_idea']


class MessageCreateForm(ModelForm):
    class Meta:
        model = TravelMessages
        fields = ['message', 'travel_group', 'message_creator']
        widgets = {
            'message_creator': HiddenInput(),
            'travel_group': HiddenInput()
        }


class MessageEditForm(ModelForm):
    class Meta:
        model = TravelMessages
        fields = ['message']


class ChecklistCreateForm(ModelForm):

    class Meta:
        model = ChecklistItems
        fields = ['checklist_item', 'checklist_creator', 'travel_group', 'item_status']
        widgets = {
            'checklist_creator': HiddenInput(),
            'travel_group': HiddenInput(),
        }


class ChecklistEditForm(ModelForm):
    class Meta:
        model = ChecklistItems
        fields = ['checklist_item', 'item_status']


SightseeingFormSet = inlineformset_factory(TravelGroup, SightseeingIdeas, extra=1, fields=('sightseeing_idea', ))
RestaurantFormSet = inlineformset_factory(TravelGroup, RestaurantIdeas, extra=1, fields=('restaurant_idea', ))
MessageFormSet = inlineformset_factory(TravelGroup, TravelMessages, extra=1, fields=('message', 'message_creator'))
# UserFormSet = inlineformset_factory(TravelGroup, AddUserForm, extra=1, fields=('email', ))

travel_group/templates/travel_group/checklist-delete.html
{% extends 'base.html' %}

{% block head %}
    {{ block.super }}
    {% block css %}
         {{ block.super }}
    {% endblock %}
{% endblock %}

{% block body %}
	<div class="form__bkg f--wrap a--ctr j--ctr pos--rel z--10">
		{% for item in site_settings %}
			<div class="form__img-wrap pos--abs o-hide">
				<img src="{{ item.checklist_photo }}" alt="Airplane" class="hero__bkg pos--abs w--100">
				<p class="caption caption--hero pos--abs">Photo credit:
				{{ item.checklist_photo_attribution }}</p>
			</div>
		{% endfor %}
		<div class="container container--wide container--center pos--rel z--10">
			<div class="grid mt--2">
				<div class="grid--6 h--100">
					<div class="form--block grid pos--rel h--100 p--2 mt--2">
						<div class="grid--10 h--100 mt--4 mb--4 pr--1 c--white">
							<form method="post">{% csrf_token %}
								<p class="ta--c c--white fz--18">Are you sure you want to delete "{{ object }}"?</p>
								<div class="f--nowrap j--ctr">
									<input type="submit" value="Confirm">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

travel_group/templates/travel_group/checklist-list.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block head %}
    {{ block.super }}
    {% block css %}
        {% compress css inline %}
            <link rel="stylesheet" type="text/x-scss" href="{% static 'travel_group/scss/travel_group.scss' %}">
        {% endcompress %}
    {% endblock %}
{% endblock %}

{% block body %}

	<div class="form__bkg f--wrap a--ctr j--ctr pos--rel z--10">
		{% for item in site_settings %}
			<div class="form__img-wrap pos--abs o-hide">
				<img src="{{ item.checklist_photo }}" alt="Airplane" class="hero__bkg pos--abs w--100">
				<p class="caption caption--hero pos--abs">Photo credit:
					{{ item.checklist_photo_attribution }}</p>
			</div>
		{% endfor %}
		<div class="container container--wide container--center pos--rel z--10">
			<div class="grid mt--2">
				<div class="grid--6">
					<div class="form--block form--block-max grid pos--rel h--100 p--2 mt--2">
						<div class="grid--10 h--100 mb--4 pr--1 c--white">
							<h3 class="c--white ta--c">Checklists</h3>
							{% for field in items %}
								<form class="checklist__items mb--2" action="{% url 'travel_checklist_edit' field.id request.user.username %}" method="post">
									{% csrf_token %}
									<div class="flex j--btwn">
										<div class="checklist__info flex a--ctr">
											<input type="hidden" name="checklist_item" value="{{ field }}">
												{{ checklist_form.item_status }}
												<label for="item_status" data-id="{{ field.id }}" data-travelid="{{ field.travel_group.id }}" data-status="{{ field.item_status }}"></label>
												<input type="text" class="checklist__item m--0 mr--2" value="{{ field }}">
												<a href="{% url 'travel_checklist_delete' field.id request.user.username %}">delete</a>
										</div>
									</div>
								</form>
							{% endfor %}
							<h4 class="c--white">Add another item</h4>
							<form action="{% url 'travel_checklist_create' travelgroup request.user.username %}" method="post">
								{% csrf_token %}
								{{ checklist_create_form.checklist_item }}
								<div class="hide">{{ checklist_create_form.item_status }}</div>
								<div class="hide">{{ checklist_create_form.checklist_creator }}</div>
								<div class="hide">{{ checklist_create_form.travel_group }}</div>
								<div class="btn-wrap">
									<input type="submit" value="Submit"/>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>




{#    <div class="body-wrap">#}
{#		<div class="hero hero--lg hero__form f--wrap a--ctr j--ctr pos--rel o-hide z--10">#}
{#			<img src="{% static 'travel_planner/images/curacao-bw.png' %}" alt="Curacao" class="hero__bkg pos--abs">#}
{#			<h1 class="h1--sm group__head pos--rel c--white grid--full ta--c z--10">Checklists</h1>#}
{#		</div>#}
{#		<div class="container container--max container--center pos--rel z--10">#}
{#			<div class="grid mt--2">#}
{#				<div class="grid--8 form-outer grid--8 blk--shadow p--2">#}
{#                    {% for field in items %}#}
{#                        <form class="checklist__items mb--2" action="{% url 'travel_checklist_edit' field.id request.user.username %}" method="post">#}
{#							{% csrf_token %}#}
{#							<div class="flex j--btwn">#}
{#								<div class="checklist__info flex">#}
{#									<input type="hidden" name="checklist_item" value="{{ field }}">#}
{#										{{ checklist_form.item_status }}#}
{#										<label for="item_status" data-id="{{ field.id }}" data-travelid="{{ field.travel_group.id }}" data-status="{{ field.item_status }}"></label>#}
{#										<input type="text" class="checklist__item m--0 mr--2" value="{{ field }}">#}
{#										<a href="{% url 'travel_checklist_delete' field.id request.user.username %}">delete</a>#}
{#								</div>#}
{#							</div>#}
{#						</form>#}
{#                    {% endfor %}#}
{#                    <h3>Add another item</h3>#}
{#                    <form action="{% url 'travel_checklist_create' travelgroup request.user.username %}" method="post">#}
{#                        {% csrf_token %}#}
{#                        {{ checklist_create_form.checklist_item }}#}
{#                        <div class="hide">{{ checklist_create_form.item_status }}</div>#}
{#                        <div class="hide">{{ checklist_create_form.checklist_creator }}</div>#}
{#                        <div class="hide">{{ checklist_create_form.travel_group }}</div>#}
{#                        <div class="btn-wrap">#}
{#                            <input type="submit" value="Submit"/>#}
{#                        </div>#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        let checkboxes = document.querySelectorAll('.checklist__info input[type="checkbox"]');
        let checklistField = document.querySelectorAll('.checklist__item');
        if(checkboxes) {
            axios.defaults.xsrfCookieName = 'csrftoken';
            axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
            axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
            let user = "{{ request.user.username }}";
            let checklist_creator_id = {{ request.user.id }};
            checkboxes.forEach( (checkbox) => {
                let checkbox_checked = checkbox.nextElementSibling.getAttribute('data-status');
                if(checkbox_checked === 'True') {
                    checkbox.checked = true;
                } else {
                    checkbox.checked = false;
                }
                checkbox.addEventListener('click', function(){
                    let itemId = parseInt(checkbox.nextElementSibling.getAttribute('data-id'));
                    let checklist_item = checkbox.nextElementSibling.nextElementSibling.value;
                    let travel_group = parseInt(checkbox.nextElementSibling.getAttribute('data-travelid'));
                    checkbox_checked = checkbox.nextElementSibling.getAttribute('data-status');

                    if(checkbox_checked === 'True') {
                        checkbox.nextElementSibling.setAttribute('data-status', 'False');
                        checkbox.checked = false;
                    } else {
                        checkbox.nextElementSibling.setAttribute('data-status', 'True');
                        checkbox.checked = true;
                    }

                    axios.post(`/travel-group/checklist-edit/${itemId}/${user}`, {
                            checklist_creator: checklist_creator_id,
                            checklist_item: checklist_item,
                            travel_group: travel_group,
                            item_status: checkbox.checked,
                            item_id: itemId
                        })
                })
            });

            checklistField.forEach( (checklist) => {
                function inputBlur(e){
                    let updatedValue = e.target.value;
                    let travel_group = parseInt(checklist.previousElementSibling.getAttribute('data-travelid'));
                    let itemId = parseInt(checklist.previousElementSibling.getAttribute('data-id'));
                    let itemStatus = checklist.parentElement.querySelector('#id_item_status');
                    checklist.setAttribute('value', updatedValue);
                        axios.post(`/travel-group/checklist-edit/${itemId}/${user}`, {
                                checklist_creator: checklist_creator_id,
                                checklist_item: updatedValue,
                                travel_group: travel_group,
                                item_status: itemStatus.checked,
                                item_id: itemId
                            })
                }
                checklist.addEventListener('click', function(){
                    checklist.addEventListener('blur', function(e){
                        inputBlur(e);
                    })
                })
                checklist.addEventListener('keyup', function(e){
                    if(e.keyCode === 9) {
                        checklist.addEventListener('blur', function(e){
                            inputBlur(e);
                        })
                    }
                })
            })
        }
    </script>
{% endblock %}

travel_group/templates/travel_group/invite-sent.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}


{% block body %}
	 <div class="form__bkg f--wrap a--ctr j--ctr pos--rel z--10">
	 		{% for photo in travelgroup.unsplash_photo.all  %}
				<div class="form__img-wrap pos--abs o-hide">
					<img src="{{photo}}" class="hero__bkg pos--abs w--100">
				</div>
			{% endfor %}
			<div class="container container--wide container--center pos--rel z--10">
				<div class="grid mt--2">
					<div class="grid--6">
						<div class="form--block form--block-max tall pos--rel p--2 mt--4">
							<h2 class="d--blk c--white ta--c txt--bb fz--18">Great! Your invite to {{ recipient }}
								has been sent!</h2>
						</div>
					</div>
				</div>
			</div>
	 </div>
{% endblock %}

travel_group/templates/travel_group/message-add.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block body %}
    <div class="body-wrap">
        <div class="img-wrap--main">
            <div class="container container--narrow container--white">
                <h2 class="ta--c">Add Message Idea</h2>
                <div class="form-wrap f--wrap">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="btn-wrap">
                            <input type="submit" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

travel_group/templates/travel_group/message-edit.html
{% extends 'base.html' %}
{% load static %}
{% load compress %}

{% block body %}
    <div class="body-wrap">
        <div class="img-wrap img-wrap--main home__img-wrap">
            <div class="container container--narrow">
				<div class="grid">
					<div class="grid--6">
						<div class="container--white pos--rel z--10">
							<h2 class="ta--c">Edit Message</h2>
							<div class="form-wrap f--wrap">
								<form action="" method="post">
									{% csrf_token %}
									{{ form.as_p }}
									<div class="btn-wrap">
										<input type="submit" value="Update">
									</div>
								</form>
							</div>
						</div>
					</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

travel_group/templates/travel_group/remove-travelers.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    {{ block.super }}
    {% block css %}
         {{ block.super }}
    {% endblock %}
{% endblock %}

{% block body %}
	<div class="form__bkg f--wrap a--ctr j--ctr pos--rel z--10">
		{% for item in site_settings %}
			<div class="form__img-wrap pos--abs o-hide">
				<img src="{{ item.restaurant_photo }}" alt="Hotel bedroom" class="hero__bkg pos--abs w--100">
				<p class="caption caption--hero pos--abs">Photo credit: {{ item.restaurant_photo_attribution }}</p>
			</div>
		{% endfor %}
		<div class="container container--wide container--center pos--rel z--10">
			<div class="grid mt--2">
				<div class="grid--6 h--100">
					<div class="form--block grid pos--rel h--100 p--2 mt--4">
						<div class="grid--10 h--100 mt--4 mb--4 pr--1 c--white">
							<form method="post">{% csrf_token %}
								<p class="ta--c c--white fz--18">Are you sure you want to delete {{ traveler }}
									from {{ travel_group }}?</p>
								<div class="hide">
									{{ form }}
								</div>
								<div class="f--nowrap j--ctr">
									<input type="submit" value="Confirm">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}